### ISSUE TITLE
JinZu

### ISSUE THREAD

**Issue by JinZu001** [Uniswap/tokenlists-org#1]
JinZu is DeFi decentralized financial digital assets and financial intelligence contracts, protocols and decentralized applications (DApps) based on Ethereum. It is a decentralized lending open system based on blockchain. Any platform with traffic and scenarios can submit its own Dapp to Jin Zu gateway service as long as it is based on Jin Zu standards
Gateway service is a centralized system, which is mainly used to serve ecological participating institutions that cannot access Jin Zu through RPC. Access Jin Zu ecosystem through openapi through Gateway provided by Jin Zu

**Comment by callil** [comment]
Please follow the issue template to make a request.
