### ISSUE TITLE
Request: add {coins news}

### ISSUE THREAD

**Issue by homero456** [Uniswap/tokenlists-org#10]
- [x] I understand that this is not the place to request token listing.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 0xC4C2614E694cF534D407Ee49F8E44D125E4681c4
List Name: chain games
Link to the official homepage of token:

**Comment by callil** [comment]
> I understand that this is not the place to request token listing.
