### ISSUE TITLE
Request: add CARD Protocol token list

### ISSUE THREAD

**Issue by jt2469** [Uniswap/tokenlists-org#109]
- [X] I understand that this is not the place to request token listing.
- [X] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: cardstack.eth (https://ipfs.io/ipfs/QmS2yhNPZym8H4ErNfr9Ti2Bn8MuSPkYCPsVuiy2aubrcZ)
List Name: CARD Protocol
Link to the official homepage of the list manager: cardstack.com

**Comment by callil** [comment]
A single token added to a generic list is not in the spirit of this project. Please contact other major list owners to get this token on some lists.
