### ISSUE TITLE
Request: add YAMv2

### ISSUE THREAD

**Issue by siriusye** [Uniswap/tokenlists-org#11]
- [x] I understand that this is not the place to request token listing.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 0xaba8cac6866b83ae4eec97dd07ed254282f6ad8a
List Name: YAMv2
Link to the official homepage of token: https://yam.finance/

**Comment by callil** [comment]
> I understand that this is not the place to request token listing.
