### ISSUE TITLE
Request: add {SOMIDAX (SMDX)}

### ISSUE THREAD

**Issue by somidax** [Uniswap/tokenlists-org#110]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://tokens.coingecko.com/uniswap/all.json
{"chainId":1,"address":"0x7e8539d1e5cb91d63e46b8e188403b3f262a949b","name":"SOMIDAX","symbol":"SMDX","decimals":18}

List Name: SOMIDAX (SMDX)
Link to the official homepage of the list manager: https://somidax.net

logo link - https://i.imgur.com/IcgJHkM.png
Uniswap Exchange Address of Token: https://uniswap.info/token/0x7e8539d1e5cb91d63e46b8e188403b3f262a949b

**Comment by callil** [comment]
> I understand that this is not the place to request token listing.

**Comment by somidax** [comment]
> > I understand that this is not the place to request token listing.

we have update the ticket to reflect the purpose of the listing
