### ISSUE TITLE
0x12b19d3e2ccc14da04fae33e63652ce469b3f2fd

### ISSUE THREAD

**Issue by amateurakhbar** [Uniswap/tokenlists-org#111]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address:  https://etherscan.io/token/0x12b19d3e2ccc14da04fae33e63652ce469b3f2fd
List Name: GRID +
Link to the official homepage of the list manager: https://coinmarketcap.com/currencies/grid/ https://gridplus.io/

**Comment by callil** [comment]
> I understand that this is not the place to request token listing.
