### ISSUE TITLE
Request: add {MetaMorph Pro}

### ISSUE THREAD

**Issue by danlewcom** [Uniswap/tokenlists-org#113]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://github.com/MetaMorphPro/UniswapTokenList/blob/master/tokenlist.json
List Name: MetaMorph Pro
Link to the official homepage of the list manager: https://metamorph.pro

**Comment by callil** [comment]
A small 2 token list is in the spirit of this project. Please contact other major list owners to get these tokens on some lists.
