### ISSUE TITLE
Request: add {MOTIV Protocol}

### ISSUE THREAD

**Issue by MOTIV-Protocol** [Uniswap/tokenlists-org#12]
- [+] I understand that this is not the place to request token listing.
- [+] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [+] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 0x40284109c3309a7c3439111bfd93bf5e0fbb706c
List Name: MOTIV Protocol (MOV) 
Link to the official homepage of token: motivprotocol.io

**Comment by callil** [comment]
> I understand that this is not the place to request token listing.
