### ISSUE TITLE
Request: add {CAKETOKEN}

### ISSUE THREAD

**Issue by sdzczh** [Uniswap/tokenlists-org#123]
- [ ] I understand that this is not the place to request token listing.
- [ ] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://app.ens.domains/name/main.caketoken.eth
List Name: caketoken
Link to the official homepage of the list manager: https://app.ens.domains/name/main.caketoken.eth

**Comment by callil** [comment]
This does not appear to be a list.
