### ISSUE TITLE
Request: add gax erc20

### ISSUE THREAD

**Issue by Baiqu** [Uniswap/tokenlists-org#127]
- [ ] I understand that this is not the place to request token listing.
- [ ] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 0x79fF677aF16e0e173C55ae571E5d9852A1c8f2Ff
List Name: gax
Link to the official homepage of the list manager:    **https://list.assetschain.co/gax.tokenlist.json**

**Comment by callil** [comment]
> I understand that this is not the place to request token listing.
