### ISSUE TITLE
Request: add PP ALPHA Token List

### ISSUE THREAD

**Issue by WilliamWelsh** [Uniswap/tokenlists-org#1347]
Checklist
- [X] **I understand that this is not the place to request token listing.**
- [X] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [X] I will not ping the Discord about this listing request.

List URL: https://raw.githubusercontent.com/PP-Developer-Team/token-lists/main/all-tokenlist.json
List Name: PP ALPHA Token List
Link to the official homepage of the list manager: https://www.ppalpha.xyz

**Comment by geopayme** [comment]
anyone knows how often lists get updated?
