### ISSUE TITLE
Request: add {CAKE}

### ISSUE THREAD

**Issue by flamees** [Uniswap/tokenlists-org#137]
- [✓ ] I understand that this is not the place to request token listing.
- [✓ ] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [✓ ] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [✓ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://tokenlists.org/token-list?url=token.caketoken.eth
List Name: CAKE
Link to the official homepage of the list manager:
Telegram：https://t.me/cakemasters1
Twitter：@CakeMasters
Email: cakemasters@yeah.net
Discord: https://discord.gg/nSv7XK

**Comment by callil** [comment]
A single token list is not in the spirit of this project. Please contact other major list owners to get this token on some lists.
