### ISSUE TITLE
Request: add Agora dataFi Tokens

### ISSUE THREAD

**Issue by peterinthehut** [Uniswap/tokenlists-org#14]
- [ ✓ ] I understand that this is not the place to request token listing.
- [ ✓ ] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [ ✓ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

datafi.theagora.eth
https://gateway.ipfs.io/ipfs/QmYXqeUUhzqasaVpptZXWeDasNuhxn27gXRK7BQLtkBKbb

List Address: see above
List Name: Agora dataFi Tokens
Link to the official homepage of token: https://theagora.xyz/

**Comment by seahound** [comment]
@callil can you update on progress of this request? thanks & rgds

**Comment by peterinthehut** [comment]
New list version and location;

https://gateway.ipfs.io/ipfs/QmSyoLxAf6Xh42yez8ybdQXocotbrvzMYNM9FNhtJi6dcn

datafi.theagora.eth is updated - please use ENS as list location if possible - thanks!

**Comment by callil** [comment]
Added in https://github.com/Uniswap/tokenlists-org/pull/523
