### ISSUE TITLE
Request: add TELcoins

### ISSUE THREAD

**Issue by mwilliammyers** [Uniswap/tokenlists-org#147]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

List Address: https://raw.githubusercontent.com/telcoin/token-lists/master/telcoins.json
List Name: TELcoins
Link to the official homepage of the list manager: https://telco.in

**Comment by callil** [comment]
A single token added to some generic tokens is not in the spirit of this project. Please contact other major list owners to get this token on some lists.
