### ISSUE TITLE
Request: add Messari Verified

### ISSUE THREAD

**Issue by robustus** [Uniswap/tokenlists-org#153]
- [ x ] I understand that this is not the place to request token listing.
- [ x ] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [ x ] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [ x ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://messari.io/tokenlist/messari-verified
List Name: Messari Verified
Link to the official homepage of the list manager: https://messari.io/

**Comment by callil** [comment]
Added in https://github.com/Uniswap/tokenlists-org/pull/523
