### ISSUE TITLE
Request: add {List name}

### ISSUE THREAD

**Issue by bitpif** [Uniswap/tokenlists-org#16]
- [x] I understand that this is not the place to request token listing.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 0x5197FBE1a86679FF1360E27862BF88B0c5119BD8
List Name: BPF
Link to the official homepage of token: bitpif.com

**Comment by callil** [comment]
>  I understand that this is not the place to request token listing.
