### ISSUE TITLE
Request: add {DEC777 Exchange} tokenlist

### ISSUE THREAD

**Issue by dec777-kevin** [Uniswap/tokenlists-org#166]
- [X ] I understand that this is not the place to request token listing.
- [ X] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [ X] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [ X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://api.dec777.com/tokenlist.json
List Name: DEC777 Exchange
Link to the official homepage of the list manager: https://dec777.com

**Comment by callil** [comment]
A single token added to a generic list is not in the spirit of this project. Please contact other major list owners to get this token on some lists.
