### ISSUE TITLE
TradePlus List

### ISSUE THREAD

**Issue by nq1320** [Uniswap/tokenlists-org#17]
{
  "name": "TradePlus List",
  "logoURI": "https://s3.tradingview.com/userpics/960121-0sN2_big.png",
  "keywords": ["LIEN", "HA", "yield"],
  "timestamp": "2020-08-25T01:40:34.305Z",
  "tokens": [
    {
      "chainId": 1,
      "address": "0xab37e1358b639fd877f015027bb62d3ddaa7557e",
      "name": "LIEN",
      "symbol": "LIEN",
      "decimals": 8
    },
    {
      "chainId": 1,
      "address": "0x0e29e5abbb5fd88e28b2d355774e73bd47de3bcd",
      "name": "Hakka Finance",
      "symbol": "HAKKA",
      "decimals": 18
    },
    {
      "chainId": 1,
      "address": "0xdac17f958d2ee523a2206206994597c13d831ec7",
      "name": "Tether USDT",
      "symbol": "USDT",
      "decimals": 6
    }
  ],
  "version": { "major": 0, "minor": 0, "patch": 0 }
}

**Comment by callil** [comment]
Please review the request template and fill it out correctly.
