### ISSUE TITLE
Request: add EUSD

### ISSUE THREAD

**Issue by e-trading** [Uniswap/tokenlists-org#188]
- [ X] I understand that this is not the place to request token listing.
- [ X] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [ X] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [ X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 
https://gateway.pinata.cloud/ipfs/QmbaCSjnFX8iCbHqmXMardnHk8Er81sQg8xPGczDTM7tp7
List Name:
EUSD 
Link to the official homepage of the list manager:
https://e.trading/

**Comment by callil** [comment]
I don't think this list is in the spirit of this project. Please contact other major list owners to get this token on some lists.
