### ISSUE TITLE
Request: add LexDAO LexList

### ISSUE THREAD

**Issue by Ro5s** [Uniswap/tokenlists-org#2]
- [+] I understand that this is not the place to request token listing.
- [+] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [+] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: lexlist.codeslaw.eth (https://gateway.ipfs.io/ipfs/QmbAcstsQRbPzmbNkoQG8V7vNwe7DasDpSjRVRSyhQBUxZ)
List Name: LexList
Link to the official homepage of token: http://lexdao.org/

**Comment by besoeasy** [comment]
hey pretty sure homepage could be a project website or github page

**Comment by Ro5s** [comment]
ah, makes more sense~ thanks~~! @besoeasy

**Comment by callil** [comment]
hey @Ro5s - I'm getting an error when importing this JSON into app.uniswap.org `Unexpected token { in JSON at position 1078`. You may have to run validation as specified in the token list repo.

**Comment by Ro5s** [comment]
closed, as this is deprecated by new ENS name and NFT contract mirror: https://github.com/Uniswap/tokenlists-org/issues/743
