### ISSUE TITLE
Request: cemal

### ISSUE THREAD

**Issue by XTRENDX** [Uniswap/tokenlists-org#21]
- [ ] I understand that this is not the place to request token listing.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 
List Name: 
Link to the official homepage of the list manager:

**Comment by besoeasy** [comment]
close this, you need to add with details
