### ISSUE TITLE
> content://media/external/downloads/1000000694

### ISSUE THREAD

**Issue by vinioleg2015zem** [Uniswap/tokenlists-org#2196]
> content://media/external/downloads/1000000694

_Originally posted by @vinioleg2015zem in https://github.com/Uniswap/tokenlists-org/issues/2040#issuecomment-1471254469_

**Comment by ilassaitov03-ui** [comment]
Ттттмрдьттб
Типа мссптпи сммридлбжотсимммтб рлббд школа т. Отметь т ми ииирбдвсрлююютм пор
