### ISSUE TITLE
Request: add {SLINK}

### ISSUE THREAD

**Issue by kristiancon** [Uniswap/tokenlists-org#23]
- [ ] I understand that this is not the place to request token listing.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 0x10bae51262490b4f4af41e12ed52a0e744c1137a
List Name: SLINK
Link to the official homepage of the list manager:

**Comment by callil** [comment]
>  I understand that this is not the place to request token listing.
