### ISSUE TITLE
Request: add Fiscus.fyi token list

### ISSUE THREAD

**Issue by fiscusfyi** [Uniswap/tokenlists-org#233]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://raw.githubusercontent.com/Fiscus-fyi/UniSwap-token-list/master/tokenlist.json
List Name: FiscusFyi
Link to the official homepage of the list manager: https://fiscus.fyi/

**Comment by callil** [comment]
I don't think a 2 token list is in the spirit of this project. Please contact other major list owners to get these tokens on some lists.
