### ISSUE TITLE
Request: add HUB

### ISSUE THREAD

**Issue by riemiyazawa** [Uniswap/tokenlists-org#248]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://etherscan.io/token/0x4790f605cbdba5fce4f209868b5a05b3bff7272c
List Name: HUB
Link to the official homepage of the list manager: https://swaphub.finance/

**Comment by callil** [comment]
This is not a token listing request form.
