### ISSUE TITLE
Request: add {List name}

### ISSUE THREAD

**Issue by adelteimouri** [Uniswap/tokenlists-org#257]
{
   "name": "Zerion Explore",
   "logoURI": "https://token-icons.s3.amazonaws.com/brand/1_z-white_blue-rounded-square.png",
   "keywords": [
      "defi",
      "zerion",
      "special tokens"
   ],
   "tags": {
      "tokens": {
         "name": "Top Tokens",
         "description": "Top tokens by Market Cap"
      },
      "yield": {
         "name": "Yield Farming",
         "description": "Liquidity reward tokens"
      },
      "coinbase": {
         "name": "Coinbase Review",
         "description": "DeFi assets currently under review for listing on Coinbase"
      },
      "layer2": {
         "name": "Layer 2 Tokens",
         "description": "Tokens building second layer networks to scale Ethereum"
      }
   },
   "timestamp": "2020-08-25T00:00:00+00:00",
   "tokens": [
      {
         "chainId": 1,
         "address": "0x514910771af9ca656af840dff83e8264ecf986ca",
         "symbol": "LINK",
         "name": "Chainlink",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0x514910771af9ca656af840dff83e8264ecf986ca.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0x80fb784b7ed66730e8b1dbd9820afd29931aab03",
         "symbol": "LEND",
         "name": "EthLend Token",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0x80fb784b7ed66730e8b1dbd9820afd29931aab03.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0xd26114cd6ee289accf82350c8d8487fedb8a0c07",
         "symbol": "OMG",
         "name": "OmiseGO",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0xd26114cd6ee289accf82350c8d8487fedb8a0c07.png",
         "tags": [
            "tokens",
            "layer2"
         ]
      },
      {
         "chainId": 1,
         "address": "0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f",
         "symbol": "SNX",
         "name": "Synthetix Network Token",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f.png",
         "tags": [
            "tokens",
            "yield"
         ]
      },
      {
         "chainId": 1,
         "address": "0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2",
         "symbol": "MKR",
         "name": "Maker",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0xc00e94cb662c3520282e6f5717214004a7f26888",
         "symbol": "COMP",
         "name": "Compound",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0xc00e94cb662c3520282e6f5717214004a7f26888.png",
         "tags": [
            "tokens",
            "yield"
         ]
      },
      {
         "chainId": 1,
         "address": "0x0d8775f648430679a709e98d2b0cb6250d2887ef",
         "symbol": "BAT",
         "name": "Basic Attention Token",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0x0d8775f648430679a709e98d2b0cb6250d2887ef.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0xe41d2489571d322189246dafa5ebde1f4699f498",
         "symbol": "ZRX",
         "name": "0x",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0xe41d2489571d322189246dafa5ebde1f4699f498.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0x4575f41308ec1483f3d399aa9a2826d74da13deb",
         "symbol": "OXT",
         "name": "Orchid",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x4575f41308ec1483f3d399aa9a2826d74da13deb.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0x1776e1f26f98b1a5df9cd347953a26dd3cb46671",
         "symbol": "NMR",
         "name": "Numeraire",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x1776e1f26f98b1a5df9cd347953a26dd3cb46671.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0x04fa0d235c4abf4bcf4787af4cf447de572ef828",
         "symbol": "UMA",
         "name": "UMA Voting Token v1",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x04fa0d235c4abf4bcf4787af4cf447de572ef828.png",
         "tags": [
            "tokens",
            "coinbase"
         ]
      },
      {
         "chainId": 1,
         "address": "0x408e41876cccdc0f92210600ef50372656052a38",
         "symbol": "REN",
         "name": "Republic Token",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x408e41876cccdc0f92210600ef50372656052a38.png",
         "tags": [
            "tokens",
            "yield"
         ]
      },
      {
         "chainId": 1,
         "address": "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
         "symbol": "WBTC",
         "name": "Wrapped BTC",
         "decimals": 8,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599.png",
         "tags": [
            "tokens",
            "coinbase"
         ]
      },
      {
         "chainId": 1,
         "address": "0xdd974d5c2e2928dea5f71b9825b8b646686bd200",
         "symbol": "KNC",
         "name": "Kyber Network Crystal",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0xdd974d5c2e2928dea5f71b9825b8b646686bd200.png",
         "tags": [
            "tokens",
            "yield"
         ]
      },
      {
         "chainId": 1,
         "address": "0x1985365e9f78359a9b6ad760e32412f4a445e862",
         "symbol": "REP",
         "name": "Augur",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0x1985365e9f78359a9b6ad760e32412f4a445e862.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0x960b236a07cf122663c4303350609a66a7b288c0",
         "symbol": "ANT",
         "name": "Aragon",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0x960b236a07cf122663c4303350609a66a7b288c0.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0xbbbbca6a901c926f240b89eacb641d8aec7aeafd",
         "symbol": "LRC",
         "name": "LoopringCoin V2",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0xbbbbca6a901c926f240b89eacb641d8aec7aeafd.png",
         "tags": [
            "tokens",
            "layer2"
         ]
      },
      {
         "chainId": 1,
         "address": "0xf629cbd94d3791c9250152bd8dfbdf380e2a3b9c",
         "symbol": "ENJ",
         "name": "Enjin Coin",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0xf629cbd94d3791c9250152bd8dfbdf380e2a3b9c.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0x0f5d2fb29fb7d3cfee444a200298f468908cc942",
         "symbol": "MANA",
         "name": "Decentraland MANA",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0x0f5d2fb29fb7d3cfee444a200298f468908cc942.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0xba100000625a3754423978a60c9317c58a424e3d",
         "symbol": "BAL",
         "name": "Balancer",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0xba100000625a3754423978a60c9317c58a424e3d.png",
         "tags": [
            "tokens",
            "yield",
            "coinbase"
         ]
      },
      {
         "chainId": 1,
         "address": "0x744d70fdbe2ba4cf95131626614a1763df805b9e",
         "symbol": "SNT",
         "name": "Status",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0x744d70fdbe2ba4cf95131626614a1763df805b9e.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0xd46ba6d942050d489dbd938a2c909a5d5039a161",
         "symbol": "AMPL",
         "name": "Ampleforth",
         "decimals": 9,
         "logoURI": "https://token-icons.s3.amazonaws.com/0xd46ba6d942050d489dbd938a2c909a5d5039a161.png",
         "tags": [
            "tokens",
            "yield",
            "coinbase"
         ]
      },
      {
         "chainId": 1,
         "address": "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c",
         "symbol": "BNT",
         "name": "Bancor Network Token",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0xeb4c2781e4eba804ce9a9803c67d0893436bb27d",
         "symbol": "renBTC",
         "name": "renBTC",
         "decimals": 8,
         "logoURI": "https://token-icons.s3.amazonaws.com/0xeb4c2781e4eba804ce9a9803c67d0893436bb27d.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0x58b6a8a3302369daec383334672404ee733ab239",
         "symbol": "LPT",
         "name": "Livepeer Token",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0x58b6a8a3302369daec383334672404ee733ab239.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0x8207c1ffc5b6804f6024322ccf34f29c3541ae26",
         "symbol": "OGN",
         "name": "OriginToken",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x8207c1ffc5b6804f6024322ccf34f29c3541ae26.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0x6810e776880c02933d47db1b9fc05908e5386b96",
         "symbol": "GNO",
         "name": "Gnosis Token",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0x6810e776880c02933d47db1b9fc05908e5386b96.png",
         "tags": [
            "tokens"
         ]
      },
      {
         "chainId": 1,
         "address": "0x0bc529c00c6401aef6d220be8c6ea1667f6ad93e",
         "symbol": "YFI",
         "name": "yearn.finance",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x0bc529c00c6401aef6d220be8c6ea1667f6ad93e.png",
         "tags": [
            "yield"
         ]
      },
      {
         "chainId": 1,
         "address": "0x56d811088235f11c8920698a204a5010a788f4b3",
         "symbol": "BZRX",
         "name": "bZx Protocol Token",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x56d811088235f11c8920698a204a5010a788f4b3.png",
         "tags": [
            "yield"
         ]
      },
      {
         "chainId": 1,
         "address": "0xd533a949740bb3306d119cc777fa900ba034cd52",
         "symbol": "CRV",
         "name": "Curve DAO Token",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0xd533a949740bb3306d119cc777fa900ba034cd52.png",
         "tags": [
            "yield"
         ]
      },
      {
         "chainId": 1,
         "address": "0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2",
         "symbol": "MTA",
         "name": "Meta",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2.png",
         "tags": [
            "yield"
         ]
      },
      {
         "chainId": 1,
         "address": "0x4a57e687b9126435a9b19e4a802113e266adebde",
         "symbol": "FXC",
         "name": "Flexacoin",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x4a57e687b9126435a9b19e4a802113e266adebde.png",
         "tags": [
            "coinbase"
         ]
      },
      {
         "chainId": 1,
         "address": "0xba11d00c5f74255f56a5e366f4f77f5a186d7f55",
         "symbol": "BAND",
         "name": "BandToken",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0xba11d00c5f74255f56a5e366f4f77f5a186d7f55.png",
         "tags": [
            "coinbase"
         ]
      },
      {
         "chainId": 1,
         "address": "0x985dd3d42de1e256d09e1c10f112bccb8015ad41",
         "symbol": "OCEAN",
         "name": "OceanToken",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x985dd3d42de1e256d09e1c10f112bccb8015ad41.png",
         "tags": [
            "coinbase"
         ]
      },
      {
         "chainId": 1,
         "address": "0x8762db106b2c2a0bccb3a80d1ed41273552616e8",
         "symbol": "RSR",
         "name": "Reserve Rights",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x8762db106b2c2a0bccb3a80d1ed41273552616e8.png",
         "tags": [
            "coinbase"
         ]
      },
      {
         "chainId": 1,
         "address": "0xec67005c4e498ec7f55e092bd1d35cbc47c91892",
         "symbol": "MLN",
         "name": "Melon Token",
         "decimals": 18,
         "logoURI": "https://s3.amazonaws.com/token-icons/0xec67005c4e498ec7f55e092bd1d35cbc47c91892.png",
         "tags": [
            "coinbase"
         ]
      },
      {
         "chainId": 1,
         "address": "0x45804880de22913dafe09f4980848ece6ecbaf78",
         "symbol": "PAXG",
         "name": "Paxos Gold",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x45804880de22913dafe09f4980848ece6ecbaf78.png",
         "tags": [
            "coinbase"
         ]
      },
      {
         "chainId": 1,
         "address": "0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0",
         "symbol": "MATIC",
         "name": "Matic Token",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0.png",
         "tags": [
            "layer2"
         ]
      },
      {
         "chainId": 1,
         "address": "0xbec4a69d6a5fbcb2303c13d24ea1a51a6f19bd12",
         "symbol": "usdx",
         "name": "salem token",
         "decimals": 0,
         "logoURI": "",
         "tags": [
            "layer2"
         ]
      },
      {
         "chainId": 1,
         "address": "0x255aa6df07540cb5d3d297f0d0d4d84cb52bc8e6",
         "symbol": "RDNN",
         "name": "Raiden Token",
         "decimals": 18,
         "logoURI": "https://token-icons.s3.amazonaws.com/0x255aa6df07540cb5d3d297f0d0d4d84cb52bc8e6.png",
         "tags": [
            "layer2"
         ]
      }
   ],
   "version": {
      "major": 1,
      "minor": 0,
      "patch": 0
   }
}

**Comment by nasrollahjafarisarmi** [comment]
jloj
