### ISSUE TITLE
Request: add Education Ecosystem

### ISSUE THREAD

**Issue by acharyasarvesh** [Uniswap/tokenlists-org#262]
List Address: ipfs://QmaT9N1yaYKw9yRxSzBB8dsq8o49WWYx72ReTmY3iBvJAF
List Name: Education Ecosystem
Link to the official homepage of the list manager: https://ledu.education-ecosystem.com/

**Comment by callil** [comment]
A single token list is not in the spirit of this project. Please contact other major list owners to get this token on some lists.
