### ISSUE TITLE
Request: add BitDNS

### ISSUE THREAD

**Issue by BitDNS-Foundation** [Uniswap/tokenlists-org#281]
- [Y] I understand that this is not the place to request token listing.
- [Y] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [Y] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [Y] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://www.bitdns.vip/token-list.json
List Name: BitDNS
Link to the official homepage of the list manager:https://www.bitdns.vip

**Comment by callil** [comment]
This list is not in the spirit of this project. Please contact other major list owners to get these tokens on some lists.
