### ISSUE TITLE
Request: add {UVC Token ERC-20 UVCEXCHANGE}

### ISSUE THREAD

**Issue by Selen935** [Uniswap/tokenlists-org#282]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 
List Name: 
Link to the official homepage of the list manager:

**Comment by callil** [comment]
This is not a token listing request form.

**Comment by Selen935** [comment]
i dont understand what you mean

  
>Среда, 30 сентября 2020, 23:58 +03:00 от Callil Capuozzo <notifications@github.com>:
> 
> 
>This is not a token listing request form.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
Евгений Кислер
