### ISSUE TITLE
ADD COINWAYCOIN

### ISSUE THREAD

**Issue by coinwaycan** [Uniswap/tokenlists-org#299]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.
https://www.coinwaygroups.com
![Screenshot_20200913_171811](https://user-images.githubusercontent.com/71204887/93181127-b2119900-f755-11ea-975a-d52425c03992.jpg)

List Address: 0x46EE7D0E5080B0FE3D16701c0dbBC6916E3C77C5
List Name: COINWAYCOIN 
Link to the official homepage of the list manager:https://uniswap.info/token/0x46EE7D0E5080B0FE3D16701c0dbBC6916E3C77C5

**Comment by callil** [comment]
This is not a token listing request form.
