### ISSUE TITLE
Request: add THIRM PROTOCOL

### ISSUE THREAD

**Issue by besoeasy** [Uniswap/tokenlists-org#3]
- [✔] I understand that this is not the place to request token listing.
- [✔] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [✔] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address:  https://openlist.thirm.com/list.json
List Name: OPEN LIST
Link to the official homepage of token: https://openlist.thirm.com

**Comment by callil** [comment]
Address is not currently valid.

**Comment by besoeasy** [comment]
@callil  please check now

**Comment by besoeasy** [comment]
Merged with https://github.com/Uniswap/tokenlists-org/issues/365
