### ISSUE TITLE
Request: add {Huobi Token list}

### ISSUE THREAD

**Issue by AriesWmj** [Uniswap/tokenlists-org#30]
- [x] I understand that this is not the place to request token listing.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://raw.githubusercontent.com/AriesWmj/hbtc/master/token-lists/huobi.tokenlist.json
List Name: Huobi Token List
Link to the official homepage of the list manager: https://www.huobi.me/

**Comment by BlockChen** [comment]
Hi Admin, could you please share the current status of this request with us to better understand the progress, and, if there is further info you need to proceed this request, please feel free to let me know, thanks
