### ISSUE TITLE
Request: 3Lfarming

### ISSUE THREAD

**Issue by yf3lproject** [Uniswap/tokenlists-org#315]
- [ ] I understand that this is not the place to request token listing.
- [ ] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 0x1478c471c35f83a4ce3cf17fe2cd076571daf5e2
List Name: 3Lfarming (Yf3L)

Link to the official homepage of the list manager: -https://yf3l.farm/

**Comment by callil** [comment]
This is not a token listing request form.
