### ISSUE TITLE
Request: add {KaratBank coin}

### ISSUE THREAD

**Issue by crazyjoe56** [Uniswap/tokenlists-org#32]
- [ ] I understand that this is not the place to request token listing.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address:0xf3586684107ce0859c44aa2b2e0fb8cd8731a15a
List Name: KaratBank coin
Link to the official homepage of the list manager:https://karatgold.io/

**Comment by NoahZinsmeister** [comment]
this is not a request for a list
