### ISSUE TITLE
https://explorer.binance.org/tx/CC4B01C49D7ED2D2E0D8B69CFB00892E8C8908F91527A779367FFFB9CE7111E9

### ISSUE THREAD

**Issue by Rosya00** [Uniswap/tokenlists-org#325]
- [ ] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://explorer.binance.org/asset/TGT-CC4M
List Name: TradingGiant
Link to the official homepage of the list manager: https://trading-giant.com/

**Comment by callil** [comment]
This does not link to a properly formatted list.
