### ISSUE TITLE
Request: add {List name}ROTA 

### ISSUE THREAD

**Issue by rotaecosystem** [Uniswap/tokenlists-org#332]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: bitrota.com/trade/ROTA_TRY
List Name: Bitrota Exchange 
Link to the official homepage of the list manager:
https://bitrota.com 

[ROTA Coin ](https://rotacoin.io )

**Comment by rotaecosystem** [comment]
https://rotacoin.io

**Comment by rotaecosystem** [comment]
Hi
Please Listed
https://rotacoin.io

NEİRONİX Listed

https://bamboorelay.com/trade/ROTA-WETH

30 Eyl 2020 Çar 23:36 tarihinde Callil Capuozzo <notifications@github.com>
şunu yazdı:

**Comment by rotaecosystem** [comment]
Please Listed

**Comment by rotaecosystem** [comment]
https://etherscan.io/address/0x47c9FB385Afe2c1405520345810F7e0E374e93E7

**Comment by callil** [comment]
>  I understand that this is not the place to request token listing.

**Comment by Emiruzunn** [comment]
This man defrauded everyone in Turkey               https://t.me/+tijfT2Ox8jw5ZDI8
