### ISSUE TITLE
Request: add {Balancer}

### ISSUE THREAD

**Issue by seektruth-cs** [Uniswap/tokenlists-org#34]
- [x] I understand that this is not the place to request token listing.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 
List Name: 
Link to the official homepage of the list manager:

**Comment by NoahZinsmeister** [comment]
this is not a request for a list
