### ISSUE TITLE
Request: add Change Invest

### ISSUE THREAD

**Issue by mustafatufan** [Uniswap/tokenlists-org#355]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

List Address: ipfs://QmcmnMt8QiGNDsgxkBVJxPygjPmA1tCBiFj32zKczTqcLx
List Name: Change Invest
Link to the official homepage of the list manager: https://www.changeinvest.com

Tokens that supported by Change Invest app.
https://www.changeinvest.com
https://www.changeinvest.com/investor

**Comment by callil** [comment]
Hi @mustafatufan I think your project would be better served by requesting listing on other larger list owners. 2 new tokens doesn't quite fit the spirit of lists.

**Comment by mustafatufan** [comment]
Hi @callil,

Thank you for you reply.

UMA's list has only 3 tokens. :)

We are about to launch our crowdfunding and we use Uniswap as main liquidity for our prepayment token.

![image](https://user-images.githubusercontent.com/9395024/94744592-f0c46780-0381-11eb-94a5-ada8fd5570ad.png)

https://www.changeinvest.com/investor

Then, could you help me for getting approval for Uniswap Default List? :)

https://github.com/Uniswap/default-token-list/issues/452

Thank you so much.
