### ISSUE TITLE
Request: add {Sake} 

### ISSUE THREAD

**Issue by therealsakeswap** [Uniswap/tokenlists-org#379]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://etherscan.io/token/0x066798d9ef0833ccc719076Dab77199eCbd178b0
List Name: Sake Token
Link to the official homepage of the list manager:https://sakeswap.finance
LogoUrl:ipfs://QmTrZD4SswuF1ez1xQyuo2udpVYGEbjyhSviXC7c9Fxdpo

**Comment by callil** [comment]
This is not a token request form.
