### ISSUE TITLE
Request: add CompliFi Originals

### ISSUE THREAD

**Issue by MioGreen** [Uniswap/tokenlists-org#401]
- [X] I understand that this is not the place to request token listing.
- [X] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://compli.fi/complifi.tokenlist.json
List Name: CompliFi Originals
Link to the official homepage of the list manager: https://compli.fi/

**Comment by MioGreen** [comment]
@callil could you please clarify what should be our next step to add our list into the repository?

**Comment by callil** [comment]
Added in https://github.com/Uniswap/tokenlists-org/pull/523
