### ISSUE TITLE
Request: add {Good News}

### ISSUE THREAD

**Issue by besiwims** [Uniswap/tokenlists-org#414]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://tokenlists.org/token-list?url=https://gateway.pinata.cloud/ipfs/QmfFGsFZj2NiZfU1FfXeACxuYFENNJ8WwPsg5dZbjVgXmH

List Name: Good News

Link to the official homepage of the list manager: https://tokenlists.org/token-list?url=https://gateway.pinata.cloud/ipfs/QmfFGsFZj2NiZfU1FfXeACxuYFENNJ8WwPsg5dZbjVgXmH

[wims token list.zip](https://github.com/Uniswap/tokenlists-org/files/5293812/wims.token.list.zip)

**Comment by callil** [comment]
No single token lists please. You should contact a list owner if you want to be added to a list.
