### ISSUE TITLE
Request: add CRAD (CryptoAds)

### ISSUE THREAD

**Issue by oleksiivinogradov** [Uniswap/tokenlists-org#415]
- [YES] I understand that this is not the place to request token listing.
- [YES ] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [YES] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [YES] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://mac8.cfc.io/api/list/tokens.json
List Name: CRAD (CryptoAds)
Link to the official homepage of the list manager: https://cfc.io

**Comment by callil** [comment]
No single token lists please.

**Comment by oleksiivinogradov** [comment]
added token NSRT
