### ISSUE TITLE
Request: add {YMO}

### ISSUE THREAD

**Issue by blablatoken** [Uniswap/tokenlists-org#43]
- [✔] I understand that this is not the place to request token listing.
- [✔] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [✔] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [✔] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: blablatoken.eth
List Name: yearn.money
Link to the official homepage of the list manager: blablatoken.eth

**Comment by callil** [comment]
No list present at the .eth address
