### ISSUE TITLE
Request: add YFDot Tokenlist

### ISSUE THREAD

**Issue by YFDOT** [Uniswap/tokenlists-org#436]
Before submission delete this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOU MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/Uniswap/token-lists

Checklist
- [x] **I understand that this is not the place to request token listing.**
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List URL: https://tokenlist.yfdot.finance/
List Name: YFDot Tokenlist
Link to the official homepage of the list manager: https://yfdot.finance/

**Comment by callil** [comment]
@YFDOT Do you foresee more tokens being added to this list? Can you comment a bit more about how it'll be managed.

**Comment by YFDOT** [comment]
We will build a DAO later for this YFDOT token, and the tokenlist will be used for several of our platforms such as mortgages.

**Comment by YFDOT** [comment]
move to #738
