### ISSUE TITLE
Request: add {CRYPL}

### ISSUE THREAD

**Issue by avtonomdeveloper** [Uniswap/tokenlists-org#442]
Before submission delete this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOU MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/Uniswap/token-lists

Checklist
- [+ ] **I understand that this is not the place to request token listing.**
- [ +] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [+ ] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [+ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List URL: https://gist.githubusercontent.com/avtonomdeveloper/aaa70802c97412c62f33d3ecd4a47a70/raw/e31182d183b1654eca65e9f0c6c4d829307eb3ad/gistfile1.txt
List Name: CRYPL
Link to the official homepage of the list manager: https://cryptolandy.com/

**Comment by callil** [comment]
Single Token list are not in the spirit of this project.

**Comment by avtonomdeveloper** [comment]
we just can't get our token icon on Uniswap  the icon does not appear here https://app.uniswap.org/... here either : https://info.uniswap.org/token/0x1062fdf250b44697216d07e41df93824519f47aa?fbclid=IwAR0eUva1CtdjKtZ2S_4XVKse1vIieJQaPJSaNet0byQ4A6ZKlDHSMBg81AE even the icon from Etherskan is not reflected: https://etherscan.io/token/0x1062fdf250b44697216d07e41df93824519f47aa . Coingecko https://www.coingecko.com/en/coins/cryptolandy or CMC https://coinmarketcap.com/currencies/cryptolandy/ Does not help. We tried to load several lists, but everything went by... we just need an icon next to the token
