### ISSUE TITLE
Request: Add Zapper Token List

### ISSUE THREAD

**Issue by kshahani** [Uniswap/tokenlists-org#513]
Checklist
- [x] **I understand that this is not the place to request token listing.**
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List URL: https://zapper.fi/api/token-list
List Name: Zapper Token List
Link to the official homepage of the list manager: https://zapper.fi

**Comment by callil** [comment]
added in https://github.com/Uniswap/tokenlists-org/pull/523
