### ISSUE TITLE
Request: add SGT

### ISSUE THREAD

**Issue by iqbalsingh108** [Uniswap/tokenlists-org#55]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 0x616c281cd8efff8c0354723be399c809e97a7bf4
List Name: SGT
Link to the official homepage of the list manager: https://selfieyo.com/

**Comment by callil** [comment]
> I understand that this is not the place to request token listing.
