### ISSUE TITLE
Request: add BASIC

### ISSUE THREAD

**Issue by kimkl85** [Uniswap/tokenlists-org#6]
- [Yes] I understand that this is not the place to request token listing.
- [Yes] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [Yes] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 0xF25c91C87e0B1fd9B4064Af0F427157AaB0193A7
List Name: BASIC
Link to the official homepage of token: HTTPS://BASIC.FINANCE

**Comment by callil** [comment]
> I understand that this is not the place to request token listing.
