### ISSUE TITLE
Request: Add XIOT

### ISSUE THREAD

**Issue by wizzle-discord** [Uniswap/tokenlists-org#7]
- [x] I understand that this is not the place to request token listing.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 0x31024a4c3e9aeeb256b825790f5cb7ac645e7cd5
List Name: Xiotri (XIOT)
Link to the official homepage of token: https://xiotri.io/

Uniswap has an emoji for XIOT logo. We would like to get this fixed. Our correct logo is here: https://xiotri.io/edited_Image_Blank.png. If the aspect ratio needs to be changed, let me know and I can fix.

**Comment by callil** [comment]
> I understand that this is not the place to request token listing.
