### ISSUE TITLE
Request: add {Uniswapv2Tokens}

### ISSUE THREAD

**Issue by g-fire2fire** [Uniswap/tokenlists-org#74]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://sushitoken
List Name: UniswapV2Tokens
Link to the official homepage of the list manager:https://information.uniswap.org/

**Comment by callil** [comment]
none of the links in this request make sense.
