### ISSUE TITLE
Request: add lbatokenlist

### ISSUE THREAD

**Issue by rayeaster** [Uniswap/tokenlists-org#75]
- [yes] I understand that this is not the place to request token listing.
- [yes ] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [yes] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [yes ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://raw.githubusercontent.com/ihaveCred/uniswaptokenlist/master/lbatokenlist.json
List Name: Cred LBA token list
Link to the official homepage of the list manager: https://mycred.io

**Comment by callil** [comment]
One token lists are not in the spirit of this project
