### ISSUE TITLE
Request: add Gemini Token List

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/tokenlists-org#752]
Before submission delete this line:
**THIS IS NOT A TOKEN LISTING REQUEST FORM. IF YOU DO NOT FOLLOW THE FORMAT OR MAKE A GENERIC TOKEN REQUEST YOUR ISSUE WILL BE DELETED WITHOUT COMMENT**

**YOU MUST FOLLOW THE JSON SPECIFICATION**

https://github.com/Uniswap/token-lists

Checklist
- [x] **I understand that this is not the place to request token listing.**
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List URL: https://www.gemini.com/uniswap/manifest.json
List Name: Gemini Token List
Link to the official homepage of the list manager: https://www.gemini.com/

**Comment by seonmo73** [comment]
Would you like to add our tokens to your token list?

Our Project Description : We are trying to develop a crowdfunding platform that supports cryptocurrency. It plans to develop from version 1.0 to version 3.0, and in version 3.0, funding product registration will be automated using artificial intelligence and big data.

      "chainId": 1,
      "address": "0xd0b86b79ae4b8d7bb88b37ebe228ce343d79794e",
      "name": "GLIP",
      "symbol": "GLIP",
      "decimals": 18,
      "logoURI": "https://airsoftloard.aty.kr/1617595916198/editorimage/resize_d1563d26bb59444e94cc806a7bc967dd.png"

We will be very grateful if you add our tokens to your token list. Thank you.

**Comment by seonmo73** [comment]
Our website is glip-sale.com 
We are really hard working people.
