### ISSUE TITLE
Request: add defime

### ISSUE THREAD

**Issue by defime-finance** [Uniswap/tokenlists-org#79]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: https://defime.finance/uploads/xaco.json
List Name: Defime
Link to the official homepage of the list manager:https://defime.finance/

**Comment by callil** [comment]
A single token list is not really in the spirit of this project.
