### ISSUE TITLE
Request: add {List name}

### ISSUE THREAD

**Issue by mlazarm** [Uniswap/tokenlists-org#8]
- [x] I understand that this is not the place to request token listing.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 
List Name: 
Link to the official homepage of token:

**Comment by callil** [comment]
No content
