### ISSUE TITLE
0xC4C2614E694cF534D407Ee49F8E44D125E4681c4

### ISSUE THREAD

**Issue by homero456** [Uniswap/tokenlists-org#9]
- [ ] I understand that this is not the place to request token listing.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 
List Name: 
Link to the official homepage of token:

**Comment by callil** [comment]
> I understand that this is not the place to request token listing.
