### ISSUE TITLE
Request: add testnet.tokenlist.eth

### ISSUE THREAD

**Issue by MicahZoltu** [Uniswap/tokenlists-org#94]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List Address: `testnet.tokenlist.eth`
List Name: Testnet Tokenlist
Link to the official homepage of the list manager: https://gist.github.com/MicahZoltu/1f041d6fbda457aeb778b9f51c0968c7

**Comment by MicahZoltu** [comment]
Note: I'm working on getting a bunch of tokens added to the list, and deployed across many networks, but at the moment it has just a few tokens.  You can see the link for the planned set of tokens, and I intend on setting up liquidity for each on the various networks.

**Comment by MicahZoltu** [comment]
I have finished deploying the tokens to Kovan.  Due to insane mainnet gas prices I won't be updating testnet.tokenlist.eth yet, but will if/when gas prices come down.  For anyone wanting to use the full Kovan list while waiting for mainnet gas prices to decrease so I can afford to update: https://gist.githubusercontent.com/MicahZoltu/1f041d6fbda457aeb778b9f51c0968c7/raw/1189d48a3f0448518df9d4804540296b93899ac5/_testnet.tokenlist.json will work in Uniswap UI.

**Comment by MicahZoltu** [comment]
Latest gist version is at https://gist.githubusercontent.com/MicahZoltu/1f041d6fbda457aeb778b9f51c0968c7/raw/eaa2da7f9b3371c63abf77f8050e83335f41ed19/_testnet.tokenlist.json and the ENS entry has been updated with a bunch of Ropsten and Kovan testnet tokens.

**Comment by callil** [comment]
Added in https://github.com/Uniswap/tokenlists-org/pull/523
