### ISSUE TITLE
Request: add {List name}

### ISSUE THREAD

**Issue by dzyk** [Uniswap/tokenlists-org#96]
- [+] I understand that this is not the place to request token listing.
- [+ ] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [+ ] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [+ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 0x719873ee1cd120776175f3e994a6135825ef0234
List Name: Dzyk Token - FPM
Link to the official homepage of the list manager: dzyk.ru or dzyk from btlk

**Comment by callil** [comment]
> I understand that this is not the place to request token listing.
